name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test
      if: matrix.node-version != '14.x'
    - run: npm test -- --coverage
      if: matrix.node-version == '14.x'
      env:
        CI: true
    - name: Post Coverage
      uses: codecov/codecov-action@v1
      if: matrix.node-version == '14.x'
      with:
        flags: unittests
        fail_ci_if_error: true
